[project]
name = "xml2json"
version = "0.1.1"
description = "Convert XML to JSON"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
xml2json = "main:read_xml_and_convert"
